extends:
  - stylelint-config-standard-scss
  - stylelint-config-clean-order
  - stylelint-prettier/recommended
rules:
  color-no-hex: true
  declaration-block-no-redundant-longhand-properties: null
  declaration-no-important: true
  import-notation: null
  max-nesting-depth: 3
  no-descending-specificity: null
  scss/percent-placeholder-pattern: null
  selector-class-pattern: null
  selector-type-no-unknown:
    - true
    - ignore:
        - custom-elements
